spring.application.name=demo
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/sampledb
spring.datasource.username=root
spring.datasource.password=machochanful
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:/db/mysql-init.sql,classpath:/db/slip-init.sql,classpath:/db/slip-media-init.sql,classpath:/db/slip-media-project-init.sql,classpath:/db/slip-header-extra-init.sql,classpath:/db/slip-return-init.sql,classpath:/db/master-setting-init.sql
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity
google.sheets.spreadsheet-id=1VIK0TdvVH7-7zc_VJmdvc7qlcMEqki5aj8UoUamHO7Y
google.sheets.range=0619newarrival!A:I
google.sheets.credentials-location=classpath:credentials.json
