spring.application.name=demo
server.port=${PORT:8080}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.datasource.url=${DB_URL:jdbc:postgresql://db.jvxnujobhwjfajhrhzfh.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:machochanful}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:/db/postgres-init.sql,classpath:/db/slip-init.sql,classpath:/db/slip-media-init.sql,classpath:/db/slip-media-project-init.sql,classpath:/db/slip-header-extra-init.sql,classpath:/db/slip-return-init.sql,classpath:/db/master-setting-init.sql
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity
google.sheets.spreadsheet-id=${GOOGLE_SHEETS_SPREADSHEET_ID:1VIK0TdvVH7-7zc_VJmdvc7qlcMEqki5aj8UoUamHO7Y}
google.sheets.range=${GOOGLE_SHEETS_RANGE:0619newarrival!A:I}
google.sheets.credentials-location=${GOOGLE_SHEETS_CREDENTIALS_LOCATION:classpath:credentials.json}
